### ISSUE TITLE
Stimmungsbarometer: gespeicherte Ergebnisse

### ISSUE THREAD

**Issue by lucalabs-de** [Leo-App/android#64]
Wenn man die Frage ändert, werden die vorherigen Ergebnisse nicht gelöscht, was zu allgemeiner Verwirrung führt. Eine Idee wäre es auch, alte Ergebnisse zu speichern, um diese zu einem späteren Zeitpunkt aufrufen zu können. Nachteile wären wiederum eine neue Tabellen-/Datenbankstruktur und ein komplizierteres Layout.

**Comment by MoritzLi** [comment]
Nach release!

**Comment by LCA311** [comment]
"Wenn man die Frage ändert, werden die vorherigen Ergebnisse nicht gelöscht, was zu allgemeiner Verwirrung führt" - Nein!

**Comment by LCA311** [comment]
Das ist eine Zeile im PHP

**Comment by MoritzLi** [comment]
Ich finde eine vertikale Trennlinie bei den Graphen gut, die markiert, wann die Frage das letzte Mal geändert wurde.

**Comment by MoritzLi** [comment]
Doch das ist dann immer ab der letzten Änderung der Frage

**Comment by lucalabs-de** [comment]
Irrelevant geworden
