### ISSUE TITLE
Security issues

### ISSUE THREAD

**Issue by gnuheidix** [Leo-App/android#80]
Ich bin durch https://heise.de/-4075100 auf dieses Projekt aufmerksam geworden und habe allgemeine IT-Sicherheitsaspekte mit einem Zeitbudget von 15 Minuten geprüft.

### Einsehbare Passwörter:
* https://github.com/LCA311/leoapp-sources/blob/master/app/src/main/java/de/slgdev/leoapp/utility/MailClient.java#L44-L45
* https://github.com/LCA311/leoapp-sources/blob/master/app/src/main/java/de/slgdev/essensbons/task/EssensbonLoginTask.java#L36
* https://github.com/LCA311/leoapp-sources/blob/master/app/src/main/java/de/slgdev/essensbons/task/QRWriteTask.java#L145-L160

### Passworthashing mit MD5 ohne Salt und Transfer über HTTP:
* https://github.com/LCA311/leoapp-sources/blob/master/app/src/main/java/de/slgdev/essensbons/task/EssensbonLoginTask.java#L28-L37
  * https://github.com/LCA311/leoapp-sources/blob/master/app/src/main/java/de/slgdev/leoapp/utility/Utils.java#L71 - HTTP

### Fehlende Zugriffskontrollen:
Das hier sind nur zwei Beispiele. Es gibt eine Menge davon.
* https://github.com/LCA311/leoapp-sources/blob/master/app/src/main/java/de/slgdev/umfragen/task/SyncSurveyTask.java#L30
  * Beispiel: https://ucloud4schools.de/ext/slg/leoapp_php/survey/getSurveys.php
* https://github.com/LCA311/leoapp-sources/blob/master/app/src/main/java/de/slgdev/leoapp/task/UpdateNameTask.java#L35-L38

Ich empfehle, die Schnittstellen sofort abzuschalten, bevor sie missbraucht werden und das Passwort des Google-Accounts zu ändern.

Die Serverseite https://github.com/LCA311/leoapp-server/ sieht leider nicht besser aus.

**Comment by lucalabs-de** [comment]
Gefixt in modular
